// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC62y8WA845kH1J5PgThkq8-dwsR0AaD7M',
    appId: '1:559149656853:web:9a940eb65b2ed8670a171c',
    messagingSenderId: '559149656853',
    projectId: 'moneytracker-app-e71bb',
    authDomain: 'moneytracker-app-e71bb.firebaseapp.com',
    storageBucket: 'moneytracker-app-e71bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzrfV5K5Y3zd3g7Lgl9aGBPjd8DwWodW8',
    appId: '1:559149656853:android:0b04014c7cbf62110a171c',
    messagingSenderId: '559149656853',
    projectId: 'moneytracker-app-e71bb',
    storageBucket: 'moneytracker-app-e71bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYK0wrh1USzKkCv68vDeHEa5mG5fMQw_I',
    appId: '1:559149656853:ios:85507d12677d3af40a171c',
    messagingSenderId: '559149656853',
    projectId: 'moneytracker-app-e71bb',
    storageBucket: 'moneytracker-app-e71bb.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYK0wrh1USzKkCv68vDeHEa5mG5fMQw_I',
    appId: '1:559149656853:ios:85507d12677d3af40a171c',
    messagingSenderId: '559149656853',
    projectId: 'moneytracker-app-e71bb',
    storageBucket: 'moneytracker-app-e71bb.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC62y8WA845kH1J5PgThkq8-dwsR0AaD7M',
    appId: '1:559149656853:web:18165d7cca18f84d0a171c',
    messagingSenderId: '559149656853',
    projectId: 'moneytracker-app-e71bb',
    authDomain: 'moneytracker-app-e71bb.firebaseapp.com',
    storageBucket: 'moneytracker-app-e71bb.firebasestorage.app',
  );
}
